# ----------------------------------------------------------------------------------#
#                                                                                   #
#   Copyright (C) 2009 - 2026 Coozila! Licensed under the MIT License.              #
#   Coozila! Team    lab@coozila.com                                                #
#                                                                                   #
# ----------------------------------------------------------------------------------#

# Location: ComfyUI/custom_nodes/studio/api.py
# Description: The API Bridge with full CORS support. Connects the Coozila 
#              Universal Canvas (OpenWebUI Frontend) to the ComfyUI Worker.

from aiohttp import web
from server import PromptServer
import json

# --- 🛡️ CORS HELPER (Essential for OpenWebUI Communication) ---

def studio_cors_response(text=None, json_data=None, status=200):
    """
    Constructs a response with mandatory headers to bypass Browser CORS blocks.
    Allows the OpenWebUI Frontend to talk to the ComfyUI Backend.
    """
    if json_data is not None:
        response = web.json_response(json_data, status=status)
    else:
        response = web.Response(text=text, content_type='text/html', status=status)
    
    # Standard CORS Headers
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
    response.headers["Access-Control-Allow-Headers"] = "Content-Type, Authorization, X-Requested-With"
    return response

# --- 🚀 API ROUTES REGISTRATION ---

# 1. INTERFACE ENDPOINT: Serves the Studio Canvas UI to OpenWebUI
@PromptServer.instance.routes.options("/coozila/studio/interface")
async def interface_options(request):
    return studio_cors_response(status=200)

@PromptServer.instance.routes.get("/coozila/studio/interface")
async def get_studio_interface(request):
    """
    This is the injection point. OpenWebUI will call this to get the 
    Studio Canvas HTML and JS logic.
    """
    canvas_html = """
    <div id="coozila-studio-canvas" style="border: 2px solid #7e22ce; padding: 20px; border-radius: 12px;">
        <h3 style="color: #a855f7;">🎬 Coozila Universal Studio Ready</h3>
        <p>Worker connected: ComfyUI (Wan 2.2)</p>
        <button onclick="console.log('Orchestrating...')">Initialize Waveform</button>
    </div>
    """
    return studio_cors_response(text=canvas_html)

# 2. RENDER ENDPOINT: Receives the JSON Payload (Worker Commands)
@PromptServer.instance.routes.options("/coozila/studio/render")
async def render_options(request):
    return studio_cors_response(status=200)

@PromptServer.instance.routes.post("/coozila/studio/render")
async def handle_studio_render(request):
    """
    Receives the dynamic JSON payload generated by the Canvas.
    Orchestrates the Wan 2.2 rendering sequence.
    """
    try:
        payload = await request.json()
        print(f"🎬 [STUDIO] Received Job for Worker: {json.dumps(payload, indent=2)}")
        
        # Integration with orchestrator.py happens here
        # result = await VideoStudioManager.run_render_pipeline(payload)
        
        return studio_cors_response(json_data={"status": "success", "message": "Render sequence started."})
    except Exception as e:
        return studio_cors_response(json_data={"status": "error", "message": str(e)}, status=500)

print("🚀 Coozila! Studio API Bridge: CORS-enabled routes registered.")