<script lang="ts">
    /**
     * @file Canvas.svelte
     * @description The primary visual dashboard for Coozila! Studio v4.2.
     * This component acts as the "Director's Monitor," synchronizing AI text outputs,
     * visual asset previews, and the technical ComfyUI render pipeline.
     */
    import { onMount, getContext } from 'svelte';
    import { fade } from 'svelte/transition';
    
    /** * @component Orchestrator - The technical control panel for Phase A/B rendering.
     * @store orchestratorStatus - Global reactive state for GPU/Worker telemetry.
     */
    import Orchestrator from './Orchestrator.svelte';
    import { orchestratorStatus } from '$lib/canvas/orchestrator.js';

    // --- PROPS: DATA INGESTION FROM THE MAIN APP ---

    /** @prop {string} scenario - The semantic script generated by the LLM (The "Director's Vision"). */
    export let scenario: string = "Awaiting director's input...";

    /** @prop {Array} assets - Real-time collection of image frames or video URLs generated by the engine. */
    export let assets: any[] = [];

    /** @prop {Object} schema - The technical JSON configuration required by the Wan 2.2 Orchestrator. */
    export let schema: any = null; 

    // --- STATE MANAGEMENT ---

    /** @state {string} activeTab - Controls the view state: 'canvas' (Visuals), 'controls' (Technical), 'generate' (Export). */
    let activeTab = 'canvas';

    /**
     * @lifecycle onMount
     * @description Establishes a "Bridge" between the AI Text Model and the Visual Canvas.
     * Attaches a global method to the window object so the AI can programmatically 
     * switch tabs or inject new technical schemas.
     */
    onMount(() => {
        window.openStudioCanvas = (newSchema = null) => {
            console.log("[Coozila] Bridge Triggered: Switching to Studio View.");
            activeTab = 'canvas';
            if (newSchema) {
                schema = newSchema; // Inject technical data directly from the AI tool
            }
        };
    });

    /**
     * @reactive tabClass
     * @description Computes Tailwind CSS classes dynamically for the navigation system.
     * Ensures high-contrast visibility for the active production phase.
     */
    $: tabClass = (id: string) =>
        `flex-1 px-3 py-2 text-[10px] font-black tracking-widest uppercase transition-all duration-200 ${
            activeTab === id
                ? 'bg-white dark:bg-gray-800 text-black dark:text-white shadow-md rounded-lg scale-[1.02]'
                : 'text-gray-500 hover:text-gray-700 dark:hover:text-gray-400'
        }`;
</script>

<div class="flex flex-col h-full w-full bg-gray-50 dark:bg-black font-primary overflow-hidden select-none">
    
    <nav class="flex space-x-1 p-1 bg-gray-200/50 dark:bg-gray-900/50 rounded-xl mb-4 mx-4 mt-4 border border-gray-300 dark:border-gray-800">
        <button class={tabClass('canvas')} on:click={() => (activeTab = 'canvas')}>Studio</button>
        <button class={tabClass('controls')} on:click={() => (activeTab = 'controls')}>Engine</button>
        <button class={tabClass('generate')} on:click={() => (activeTab = 'generate')}>Master</button>
    </nav>

    <main class="flex-1 overflow-y-auto px-4 custom-scrollbar">
        
        {#if activeTab === 'canvas'}
            <div in:fade class="flex flex-col gap-6 pb-10">
                
                <section class="p-4 rounded-2xl bg-white dark:bg-gray-950 border border-gray-200 dark:border-gray-800 shadow-sm">
                    <header class="flex items-center gap-2 mb-3">
                        <div class="w-1.5 h-1.5 rounded-full bg-purple-600 animate-pulse"></div>
                        <h3 class="text-[9px] font-black uppercase tracking-widest opacity-40">Active Scenario</h3>
                    </header>
                    <article class="text-xs leading-relaxed text-gray-700 dark:text-gray-300 italic">
                        "{scenario}"
                    </article>
                </section>

                <section class="w-full">
                    <header class="mb-3 px-1">
                        <h3 class="text-[9px] font-black uppercase tracking-widest opacity-30">Production Frames</h3>
                    </header>
                    <div class="grid grid-cols-2 gap-3">
                        {#each assets as asset}
                            <div class="aspect-video bg-gray-900 rounded-xl border border-gray-800 overflow-hidden shadow-inner group relative">
                                <img src={asset.url} alt="Frame" class="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity" />
                                <div class="absolute bottom-2 left-2 bg-black/60 px-1.5 py-0.5 rounded text-[7px] font-mono text-white opacity-0 group-hover:opacity-100 transition-opacity">
                                    {asset.id || 'RAW_FRAME'}
                                </div>
                            </div>
                        {/each}
                        
                        {#if assets.length === 0}
                            <div class="col-span-2 py-12 flex flex-col items-center justify-center border-2 border-dashed border-gray-200 dark:border-gray-900 rounded-2xl opacity-20">
                                <span class="text-[10px] font-black uppercase tracking-widest">No Assets Generated</span>
                            </div>
                        {/if}
                    </div>
                </section>
            </div>
            
        {:else if activeTab === 'controls'}
            <div in:fade class="flex flex-col gap-6">
                <Orchestrator {schema} />

                <section class="p-5 rounded-3xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-950 shadow-sm">
                    <h3 class="text-[10px] font-black mb-4 uppercase tracking-[0.2em] text-purple-600">Pipeline Config</h3>
                    <div class="space-y-3">
                        <div class="flex justify-between text-[10px] font-bold">
                            <span class="opacity-40 uppercase tracking-tighter">Model</span>
                            <span class="text-gray-400">Wan 2.2 (14B)</span>
                        </div>
                        <div class="flex justify-between text-[10px] font-bold">
                            <span class="opacity-40 uppercase tracking-tighter">Sampler</span>
                            <span class="text-gray-400">Uni_PC / Simple</span>
                        </div>
                        <div class="flex justify-between text-[10px] font-bold">
                            <span class="opacity-40 uppercase tracking-tighter">Optimization</span>
                            <span class="text-green-500">FP8 Quantized</span>
                        </div>
                    </div>
                </section>
            </div>

        {:else if activeTab === 'generate'}
             <div in:fade class="p-10 text-center space-y-4 opacity-20">
                <div class="text-4xl">🎬</div>
                <h3 class="text-xs font-black uppercase tracking-widest">Master Handoff</h3>
                <p class="text-[10px] font-bold">Export for DaVinci Resolve (OTIO) will appear here after Phase B completion.</p>
             </div>
        {/if}
    </main>

    <footer class="p-4 border-t border-gray-200 dark:border-gray-800 bg-gray-50/50 dark:bg-black/50">
        <div class="flex justify-between items-center px-1">
            <div class="flex items-center gap-2">
                <div class="w-1.5 h-1.5 rounded-full {$orchestratorStatus.state === 'RENDERING' ? 'bg-orange-500 animate-pulse' : 'bg-green-500'}"></div>
                <span class="text-[9px] font-black uppercase tracking-widest opacity-40">
                    {$orchestratorStatus.state}
                </span>
            </div>
            <span class="text-[9px] font-black opacity-20 uppercase tracking-tighter">Coozila Engine v4.2</span>
        </div>
    </footer>
</div>

<style>
    /* Professional scrollbar styling for seamless integration with sidebar layouts */
    .custom-scrollbar::-webkit-scrollbar { width: 3px; }
    .custom-scrollbar::-webkit-scrollbar-thumb {
        background: rgba(126, 34, 206, 0.2);
        border-radius: 10px;
    }
</style>